steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/app-bordados/app-bordados:$COMMIT_SHA', 
      '--build-arg', 'VITE_FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}',
      '--build-arg', 'VITE_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/app-bordados/app-bordados:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'remix-bordado-m-gico-matrizes-de-bordado'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/app-bordados/app-bordados:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Link environment variables
      - '--set-env-vars'
      - 'FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL},GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
      # Ensure latest revision is always used
      - '--tag'
      - 'latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/app-bordados/app-bordados:$COMMIT_SHA'

substitutions:
  _FIREBASE_DATABASE_URL: 'https://bordado-aff87-default-rtdb.firebaseio.com/'
  _FIREBASE_PROJECT_ID: 'bordado-aff87'
  _GCS_BUCKET_NAME: 'appbordados'

options:
  logging: CLOUD_LOGGING_ONLY
